"""last_seen, bio added in usermodel

Revision ID: 28874eac7690
Revises: 178f56955a69
Create Date: 2020-09-22 19:36:54.038603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28874eac7690'
down_revision = '178f56955a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=127), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
