"""notifications table

Revision ID: e0b4fb708760
Revises: 6898c1cde10b
Create Date: 2020-10-23 23:17:10.244777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b4fb708760'
down_revision = '6898c1cde10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Notification_name'), 'Notification', ['name'], unique=False)
    op.create_index(op.f('ix_Notification_timestamp'), 'Notification', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Notification_timestamp'), table_name='Notification')
    op.drop_index(op.f('ix_Notification_name'), table_name='Notification')
    op.drop_table('Notification')
    # ### end Alembic commands ###
